sprite $modifiers_sharedcoremachineG1 [120x120/16z] {
xTf50GCm44N1TV3zksqlPSRGl6De16Jh94cIb2_tDDi2pa_grasQmFbP0xjSBfVBvTQL7kn-xDQs1curSQkQkBMMMpExtDgN9vlRvNAvN2wtzitjShbSBfUR
kcmYbvjMRbPparPk6hZxFd7zBt2vN2wNsmOsN_S7kOkvJKcIj04
}

GCPColoring(modifiers_ sharedcoremachineG1)
!define GCP_modifiers_ sharedcoremachineG1(alias, name) GCPEntity(alias, name, modifiers_ sharedcoremachineG1, modifiers_ sharedcoremachineG1)
