sprite $modifiers_storage [120x120/16z] xTT10G0G4031Qw1_Mpy10DnCWNrlB080GDaWSrStcYkxkhgwkgDqTGS1-45TFwYhgwlh1tNz880VrFM3khgwkdvGrmy20501
}

GCPColoring(modifiers_storage)
!define GCP_modifiers_storage(alias, name) GCPEntity(alias, name, modifiers_storage, modifiers_storage)
