sprite $modifiers_sharedcoremachineF1 [120x120/16z] {
xTh50OGm04N1tm7zLxlkhiJc7R4vOKbobYH9cdvS0NPR0NLNjUxqfmgmsnfskLmkbylDZPxi_ThDgW9kYhX94JTZkUdPvRx_02tgShbSxdNLkbmkbtijSBbS
BfVBvNBDBt2vN2wNMmQslcu6kOfrcv8aQGa
}

GCPColoring(modifiers_sharedcoremachineF1)
!define GCP_modifiers_sharedcoremachineF1(alias, name) GCPEntity(alias, name, modifiers_sharedcoremachineF1, modifiers_sharedcoremachineF1)
